name: Build and Push Docker Image

on:
  push:
    branches:
      - main # หรือชื่อ branch ที่คุณต้องการใช้

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mojisejr/jaothui-renderer:v1.0
          build-args: |
            notify_key=${{secrets.NOTIFY_KEY}}
            line_uri=${{secrets.LINE_URI}}
            jwt_secret=${{secrets.JWT_SECRET}}
            DATABASE_URL=${{secrets.DATABASE_URL}}
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.DROPLET_HOST}}
          username: ${{secrets.DROPLET_USER}}
          password: ${{secrets.DROPLET_PASS}}
          # key: ${{secrets.DROPLET_SSH}}
          script: |
            docker image rm mojisejr/jaothui-renderer:v1.0
            docker pull mojisejr/jaothui-renderer:v1.0
            docker stop jaothui-renderer 
            docker rm jaothui-renderer
            docker run -d  \
            --restart always \
            --name jaothui-renderer \
            -p 4444:4444
            -e notify_key=${{secrets.NOTIFY_KEY}} \
            -e line_uri=${{secrets.LINE_URI}} \
            -e jwt_secret=${{secrets.JWT_SECRET}} \
            -e DATABASE_URL=${{secrets.DATABASE_URL}} \
            mojisejr/jaothui-renderer:v1.0
            docker container logs jaothui-renderer
